### ISSUE TITLE
Can't Export Model: Permission Denied (Linux)

### ISSUE THREAD

**Issue by cow-killer** [ssbucarlos/smash-ultimate-blender#63] opened 2022-01-09 18:10 UTC
Greetings, I'm trying to export a Zelda model on Linux with Blender 3.0. I'm able to import successfully, but exporting leaves a permission denied error:
![blender_export_error](https://user-images.githubusercontent.com/12868939/148694793-eee3e82b-b43e-4333-8abf-eb0fc1af081a.png)

Any ideas?

**Comment by ScanMountGoat** [comment] 2022-01-10 02:16
The numshexb export is relying on a Windows only executable at the moment. You should be able to disable numshexb export in the settings window as a workaround for now. 

There's a change to numshexb export that will work cross platform that I haven't merged yet. Once this issue is closed, download the latest version from github and reinstall the plugin.

**Comment by cow-killer** [comment] 2022-01-10 16:40
> You should be able to disable numshexb export in the settings window as a workaround for now

After disabling that option before exporting the model I'm still getting the same error message. In fact unchecking everything else doesn't make a difference.

**Comment by ScanMountGoat** [comment] 2022-01-10 16:59
It looks like the executable is used in more places than I thought. You'll have to wait for update to be able to export.

**Comment by ScanMountGoat** [comment] 2022-01-11 01:00
@cow-killer I'm no longer having this issue on the new update. Please reinstall the plugin and let me know if you're still having the same error.

**Comment by cow-killer** [comment] 2022-01-11 03:28
Export works now. After making changes to the model, however, I'm getting this:
![Screenshot_2022-01-10_22-27-04](https://user-images.githubusercontent.com/12868939/148876355-99ab5364-0621-4f04-9187-3b3fac1a4d83.png)

**Comment by ScanMountGoat** [comment] 2022-01-11 03:32
Glad to hear it. 

Your model isn't properly triangulated. This is usually caused by loose vertices. See https://github.com/ssbucarlos/smash-ultimate-blender/wiki/Read-this-if-you-have-export-issues.-Or-want-to-avoid-Export-Issues for how to clean up the geometry. Making more helpful error messages is currently a WIP.

**Closed by ScanMountGoat** 2022-01-11 03:32 UTC
Labels: bug
