### ISSUE TITLE
Frame Rate issue

### ISSUE THREAD

**Issue by puli2004** [ssbucarlos/smash-ultimate-blender#150] opened 2022-10-01 18:01 UTC
For some reason when playing animations with the plugin. It only goes 20FPS when the frame rate is only set to 60. This is the only addon that is causing this problem.

**Comment by ScanMountGoat** [comment] 2022-10-01 18:26
Are you still getting 20 fps even if the frame rate is set to 30 or 60? Your computer may not be fast enough to render animations at full speed. You can also try setting the shading mode to solid in the Blender viewport and see if that speeds things up. SSBH Editor is more lightweight and tends to run at full speed even on weaker laptops (debug shading modes run faster). You can't edit animations in SSBH Editor of course.

**Comment by puli2004** [comment] 2022-10-02 21:55
No it keeps it on 20FPS. 30 FPS and 60 FPS don’t get passed. And my hardware is ok to run a big application.

**Comment by ScanMountGoat** [comment] 2022-10-02 22:06
Sounds like your CPU performance isn't good enough to do 60 fps. My desktop can do about 88 fps in solid mode for Mario's animations for reference. My old laptop gets about 14 fps. The priority right now is fixing bugs and implementing missing features. There may be things we can do in the future to improve playback performance. For now, you can either deal with slow playback, enable frame skipping in Blender, or test in SSBH Editor to see how fast the animations will look.

**Comment by ssbucarlos** [comment] 2022-10-03 04:59
Closing since the issue is outside the scope of the plugin.

**Closed by ssbucarlos** 2022-10-03 04:59 UTC

**Comment by puli2004** [comment] 2022-10-03 19:32
Ok
