### ISSUE TITLE
Armature and Mesh Rotation Importing Issues

### ISSUE THREAD

**Issue by MadMax1960** [ssbucarlos/smash-ultimate-blender#116] opened 2022-06-24 22:02 UTC
I have an issue whenever I touch a model I've begun to link bones too (As in begin pairing said armatures bones to smash bones) it will always import sideways. This includes scaling, editing any bones, and adding new bones to it. Even upon updating bone pairing list, or rebuilding bone list, I always have to make a new armature. 

Along with that, I always have to rotate my mesh -90 degrees to make it import upright. 

Link to blend: https://cdn.discordapp.com/attachments/831687902824103977/990014016980144168/kaneki__kagune_4.blend

Link to mod files: https://cdn.discordapp.com/attachments/831687902824103977/990014070201667614/c04_-_Copy.rar

**Comment by ScanMountGoat** [comment] 2022-06-26 20:33
By "import sideways" do you mean the model appears rotated in game compared to in Blender? If you're making a combined skeleton, you need to make sure to apply the transforms of the armatures before combining. I'll take a look at the files later to try and see what the issue is. This should be something we can automatically detect before the export happens from Blender.

**Comment by MadMax1960** [comment] 2022-06-26 20:44
Yeah I've triple checked it was apply transforms since I was editing scale originally, but I can replicate with that blend by editing anything involving the skeleton. 

And yes I mean importing sideways, I checked in StudioSB and the non smash skeleton got imported -90 on x axis almost 100% of the time (sometimes -90 on z too). However, seems to sometimes be fixed by parenting root of non smash skeleton to smash skeleton, which is what you should always do yeah but it doesn't seem to fix it 100% of the time. 

Mesh issue happens for me no matter what, always have to rotate it -90 on y then apply transforms or it imports laying forwards.

**Comment by ScanMountGoat** [comment] 2022-06-27 18:36
It looks like the rotation correction for in game models doesn't get applied on import. This would explain why the model exports as being rotated by 90 degrees. You'll need to rotate the model like you mentioned for now until we implement the fix.

**Comment by ScanMountGoat** [comment] 2022-07-01 15:12
This should be fixed on the latest commit. It shouldn't matter if transforms are applied or not as long as the model is oriented correctly in Blender (standing up).

**Closed** 2022-07-08 17:19 UTC
Labels: bug
