### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by Ricod7** [ssbucarlos/smash-ultimate-blender#30] opened 2021-09-07 01:53 UTC
I downloaded your `smash-ultimate-blender` plugin tool for Blender. However, Blender throws an error when I try to enable it after trying to install it in Blender. I am on `Linux` with the latest Blender version (2.93) installed through `Steam`. I have a screenshot of the error:

![Screenshot from 2021-09-06 21-13-31](https://user-images.githubusercontent.com/17516787/132272296-83c620af-f3dd-44c6-a867-cd48d3c5d78a.png)

This tool works on the Windows Blender version as my brother has it installed & has showed me it.

Thank you for your support/help.

**Comment by ScanMountGoat** [comment] 2022-01-01 04:09
@Ricod7 This should be working on the latest version. We have versions of the ssbh_data_py package included for Windows, Linux, and MacOS.

**Comment by Ricod7** [comment] 2022-01-01 19:53
@ScanMountGoat Oh wow I forgot about this.. Thank you (& @ssbucarlos) for your help!

If I ever use or get on Linux again, this will definitely help me out! I'm on Windows now.

**Comment by ScanMountGoat** [comment] 2022-01-11 03:41
Closing since the latest commit is confirmed to work on Linux and MacOs.

**Closed by ScanMountGoat** 2022-01-11 03:41 UTC
Labels: bug, Research Needed
